name             'gexample'
maintainer       'Jeff Owens'
maintainer_email 'admin@centralstop.com'
license          'All rights reserved'
description      'Installs/Configures gexample'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'openssh'
depends 'git'
depends 'chef-solo-search'
depends 'sudo'
depends 'users'
depends 'nodejs'
depends 'npm'
depends 'nginx'
depends 'runit'
